# Generated by Django 3.1.7 on 2022-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(default='Testing Description', max_length=40000),
            preserve_default=False,
        ),
    ]
