# Generated by Django 3.1.7 on 2021-02-26 21:31

from django.db import migrations, models
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210226_2011'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default=180905330, max_length=10),
            preserve_default=False,
        ),
    ]
