# Generated by Django 3.1.7 on 2021-03-03 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210301_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
