# Generated by Django 3.1.7 on 2021-03-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210304_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='applied', max_length=100),
        ),
    ]
