# Generated by Django 3.1.7 on 2021-08-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_faculty_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours_per_week',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_extendable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='domains_of_interest',
            field=models.CharField(max_length=65000, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_is_complete', models.BooleanField()),
                ('feedback', models.CharField(max_length=20000)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.application')),
            ],
        ),
    ]
