# Generated by Django 3.1.7 on 2021-08-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210817_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.application'),
        ),
    ]
