# Generated by Django 3.1.7 on 2021-08-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210826_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_building',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcome',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(max_length=65000),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='domains_of_interest',
            field=models.TextField(max_length=65000, null=True),
        ),
    ]
